name: al_ameen
description: "A new Flutter al_ameen project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  #  google_sign_in: ^6.1.0
  sqflite: ^2.3.0
  path: ^1.8.2
  # Local Data Cache
  shared_preferences: ^2.1.0
  #dartz: ^0.10.1
  url_launcher: ^6.0.20
  #  image_picker: ^0.8.7+4
  get_storage: ^2.1.1
  win32: ^5.9.0 # or the latest version
  archive: ^3.5.0  # or the latest version
  #  url_launcher: ^6.1.12
  #  flutter_rating_bar: ^4.0.1
  # Lottie Animation
  lottie: ^2.3.0
  animated_text_kit: ^4.2.1
#  flutter_svg: ^1.1.6
#  # printers
#  esc_pos_printer: ^4.1.0
#  esc_pos_utils: ^1.0.0
  http: ^1.1.0
#  image: ^3.3.0
#  pdf: ^3.8.4
#  syncfusion_flutter_pdf: ^23.1.40
#  screenshot: ^2.1.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
#  qr_code_scanner: ^1.0.1
  wave: ^0.2.2
#  url_launcher: ^6.2.1
  open_file: ^3.3.2
  awesome_snackbar_content: ^0.1.1
  video_player: ^2.9.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  icon_badge: ^1.0.0
  fl_chart: ^0.70.0
  # device_preview: ^1.1.0
#  rename: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/splash.png"
  adaptive_icon_background: "#FFFFFF"
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/splash.png
    - assets/icons/
    - assets/svg/
    - assets/lottie/
    - assets/image/
    - assets/fonts/
    - assets/Video/
    - assets/bank/

video_player:
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
